"""per-user resume ids

Revision ID: 0fda5fd18c59
Revises: 32ed9f4555a3
Create Date: 2025-11-09 01:16:06.346239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fda5fd18c59'
down_revision: Union[str, Sequence[str], None] = '32ed9f4555a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) add column as nullable to allow backfill
    op.add_column('resumes', sa.Column('user_resume_id', sa.Integer(), nullable=True))

    # 2) backfill per-user incremental ids (1..N) ordered by existing global id
    op.execute(
        """
        WITH numbered AS (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY id) AS rn
            FROM resumes
        )
        UPDATE resumes r
        SET user_resume_id = n.rn
        FROM numbered n
        WHERE n.id = r.id
        """
    )

    # 3) enforce NOT NULL and add index/unique constraint
    op.alter_column('resumes', 'user_resume_id', existing_type=sa.Integer(), nullable=False)
    op.create_index(op.f('ix_resumes_user_resume_id'), 'resumes', ['user_resume_id'], unique=False)
    op.create_unique_constraint('uq_resumes_user_localid', 'resumes', ['user_id', 'user_resume_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_resumes_user_localid', 'resumes', type_='unique')
    op.drop_index(op.f('ix_resumes_user_resume_id'), table_name='resumes')
    op.drop_column('resumes', 'user_resume_id')
    # ### end Alembic commands ###
